<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><RootNamespace>Jellyfin.Plugin.Randomizer</RootNamespace><AssemblyName>Jellyfin.Plugin.Randomizer</AssemblyName></PropertyGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /><PackageReference Include="Jellyfin.Controller" Version="$(JellyfinVersion)" ExcludeAssets="runtime" /><PackageReference Include="Jellyfin.Model" Version="$(JellyfinVersion)" ExcludeAssets="runtime" /><PackageReference Include="Jellyfin.Common" Version="$(JellyfinVersion)" ExcludeAssets="runtime" /><PackageReference Include="Jellyfin.Data" Version="$(JellyfinVersion)" ExcludeAssets="runtime" /></ItemGroup><ItemGroup><EmbeddedResource Include="Configuration/configPage.html" /><EmbeddedResource Include="Web/randomizer.js" /><EmbeddedResource Include="Web/randomizer.css" /></ItemGroup></Project>